//
// DeviceDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceDto: Codable {

    public var _id: String?
    public var deviceOs: String?
    public var deviceOsVersion: String?
    public var appVersion: String?
    public var lastLoginUtcDateTime: Date?
    public var lastLoginIpAddress: String?

    public init(_id: String?, deviceOs: String?, deviceOsVersion: String?, appVersion: String?, lastLoginUtcDateTime: Date?, lastLoginIpAddress: String?) {
        self._id = _id
        self.deviceOs = deviceOs
        self.deviceOsVersion = deviceOsVersion
        self.appVersion = appVersion
        self.lastLoginUtcDateTime = lastLoginUtcDateTime
        self.lastLoginIpAddress = lastLoginIpAddress
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case deviceOs
        case deviceOsVersion
        case appVersion
        case lastLoginUtcDateTime
        case lastLoginIpAddress
    }


}

