//
// ExternalLoginRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ExternalLoginRequest: Codable {

    public var loginProvider: String

    public init(loginProvider: String) {
        self.loginProvider = loginProvider
    }


}

