//
// RemoveExternalLoginRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RemoveExternalLoginRequest: Codable {

    public var loginProvider: String
    public var providerKey: String

    public init(loginProvider: String, providerKey: String) {
        self.loginProvider = loginProvider
        self.providerKey = providerKey
    }


}

