//
// UserDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserDto: Codable {

    public var userId: String?
    public var username: String?
    public var email: String?
    public var phoneNumber: String?

    public init(userId: String?, username: String?, email: String?, phoneNumber: String?) {
        self.userId = userId
        self.username = username
        self.email = email
        self.phoneNumber = phoneNumber
    }


}

