//
// TokenResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TokenResponse: Codable {

    public enum TokenType: String, Codable { 
        case deviceverification = "deviceVerification"
        case smsclientverification = "smsClientVerification"
        case smsserververification = "smsServerVerification"
        case refresh = "refresh"
        case access = "access"
    }
    public var token: String?
    public var tokenType: TokenType?
    public var expires: Date?
    public var apiError: ApiError?

    public init(token: String?, tokenType: TokenType?, expires: Date?, apiError: ApiError?) {
        self.token = token
        self.tokenType = tokenType
        self.expires = expires
        self.apiError = apiError
    }


}

