//
// UserRegisterRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserRegisterRequest: Codable {

    public var username: String
    public var email: String
    public var password: String
    public var confirmPassword: String?
    public var tos: Bool

    public init(username: String, email: String, password: String, confirmPassword: String?, tos: Bool) {
        self.username = username
        self.email = email
        self.password = password
        self.confirmPassword = confirmPassword
        self.tos = tos
    }


}

