//
// DeviceRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceRequest: Codable {

    public var _id: String
    public var deviceOs: String
    public var deviceOsVersion: String
    public var appVersion: String
    public var fcmToken: String

    public init(_id: String, deviceOs: String, deviceOsVersion: String, appVersion: String, fcmToken: String) {
        self._id = _id
        self.deviceOs = deviceOs
        self.deviceOsVersion = deviceOsVersion
        self.appVersion = appVersion
        self.fcmToken = fcmToken
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case deviceOs
        case deviceOsVersion
        case appVersion
        case fcmToken
    }


}

