//
// VerifyPhoneRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VerifyPhoneRequest: Codable {

    public var code: String
    public var phoneNumber: String

    public init(code: String, phoneNumber: String) {
        self.code = code
        self.phoneNumber = phoneNumber
    }


}

